[package]
name = "starfinder"
version = "2.0.0"
edition = "2024"
license-file = "LICENSE"
description = "starfinder is a Rust & Python package that provides functionality to read, process, and render star data from the Tycho-2 catalog. It's built with Rust for performance and exposes a Python API for ease of use."
homepage = "https://github.com/djmango/starfinder"
repository = "https://github.com/djmango/starfinder"
readme = "README.md"
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE",
]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
csv = "1"
directories = "6"
image = "0.25"
nalgebra = "0.34"
# pyo3 = "0.22.2"
reqwest = { version = "0.12", features = ["blocking"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = "0.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "starfinder"
crate-type = ["cdylib", "rlib"]
